// GENERATED by tauri-specta. Do not edit.
// Regenerated on every debug run of the Rust backend (see lib.rs).

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  The detected hardware profile and the tier in force.
	 * 
	 *  Drives the Settings screen (§8: shown "in plain language. This is a nice UI
	 *  moment, not an apology").
	 */
	getHardwareProfile: () => __TAURI_INVOKE<HardwareProfile>("get_hardware_profile"),
	/**
	 *  Override the detected tier, or clear the override with `None`.
	 * 
	 *  §8 requires a manual override. Someone whose GPU is misdetected, or who wants
	 *  to see the Tier 0 experience, should not have to fight the app.
	 */
	setTierOverride: (tier: 
/**  < 8 GB RAM, or no hardware decode, or <= 2 physical cores. */
"modest" | 
/**  8-16 GB RAM, hardware decode present, >= 4 cores. */
"standard" | 
/**  >= 16 GB RAM, discrete GPU or strong iGPU, >= 6 cores. */
"capable" | null) => __TAURI_INVOKE<HardwareProfile>("set_tier_override", { tier }),
	/**
	 *  Whether a capability is available under the effective tier.
	 * 
	 *  The ONLY way a feature may ask about hardware (§8).
	 */
	hasCapability: (capability: Capability) => __TAURI_INVOKE<boolean>("has_capability", { capability }),
	/**  Where portable data lives, for the Settings screen to show honestly. */
	getDataDir: () => __TAURI_INVOKE<string>("get_data_dir"),
	/**
	 *  Deliberately panic, to prove the crash handler works.
	 * 
	 *  Phase 1 exit criterion: "a deliberately-triggered panic writes a crash log and
	 *  shows a graceful error screen." An exit criterion that cannot be exercised is
	 *  not evidence, so the trigger ships — in debug builds only.
	 */
	debugTriggerPanic: () => __TAURI_INVOKE<void>("debug_trigger_panic"),
	/**
	 *  The frontend has painted. Reveal the window and record cold start.
	 * 
	 *  This is what makes Phase 1's "< 2 s to interactive" a real measurement rather
	 *  than a measurement of window creation.
	 */
	frontendReady: () => __TAURI_INVOKE<number>("frontend_ready"),
};

/* Types */
/**  What a tier permits. Features ask about a `Capability`, never about hardware. */
export type Capability = 
/**
 *  Embed catalogue DOCUMENTS on device. Tier 1+.
 * 
 *  Note ADR-0015: embedding a QUERY is permitted on every tier and is
 *  deliberately not gated here. The asymmetry is scale — hundreds of
 *  thousands of long documents versus one ~30-token query.
 */
"local_document_embedding" | 
/**
 *  VAD-based subtitle alignment. Tier 1+. Below that: hash match, duration
 *  heuristics, and a manual nudge that is remembered per file.
 */
"vad_subtitle_alignment" | 
/**  Intro/credit detection across a season. Tier 1+. */
"binge_detection" | 
/**  Playback above 1080p by default. Tier 1+ (users may override). */
"high_res_playback" | 
/**  Face recognition in the pause overlay. Tier 2 only. */
"face_recognition" | 
/**  Whisper-based subtitle generation. Tier 2 only. */
"local_transcription" | 
/**  Background pre-embedding of the catalogue. Tier 2 only. */
"background_pre_embedding" | 
/**  Full motion design: hover previews, background blur, parallax. */
"full_motion";

/**
 *  What detection actually found. Shown verbatim in Settings (§8: "in plain
 *  language. This is a nice UI moment, not an apology").
 *  Note the integer widths. Specta refuses to export u64/usize/i64 across the IPC
 *  boundary because JavaScript numbers are f64 and would silently lose precision
 *  above 2^53. u32 is not a workaround — it is the correct type here: 4 billion MB
 *  is four petabytes of RAM, and nobody has 4 billion CPU cores.
 */
export type HardwareProfile = {
	total_memory_mb: number,
	physical_cores: number,
	logical_cores: number,
	cpu_brand: string,
	gpu_name: string | null,
	hardware_decode: boolean,
	/**  The tier detection arrived at, before any override. */
	detected_tier: Tier,
	/**  The tier actually in force. Differs only when the user has overridden. */
	effective_tier: Tier,
	overridden: boolean,
};

/**  The three tiers from §8. */
export type Tier = 
/**  < 8 GB RAM, or no hardware decode, or <= 2 physical cores. */
"modest" | 
/**  8-16 GB RAM, hardware decode present, >= 4 cores. */
"standard" | 
/**  >= 16 GB RAM, discrete GPU or strong iGPU, >= 6 cores. */
"capable";

