import type { Destination } from "@/lib/store";

const COPY: Record<Destination, { title: string; body: string; phase: string }> = {
  home: {
    title: "Home",
    body: "Continue Watching first, then adaptive rails generated by the discovery engine.",
    phase: "Phase 18",
  },
  films: {
    title: "Films",
    body: "Browsable catalogue by genre, decade, country, director, movement and collection.",
    phase: "Phase 18",
  },
  tv: {
    title: "TV Shows",
    body: "Series with proper season and episode handling. Anime is identifiable and filterable.",
    phase: "Phase 18",
  },
  watchlist: {
    title: "Watchlist",
    body: "Saved items with lists, priority, and smart views like \u201Cavailable now\u201D.",
    phase: "Phase 19",
  },
  live: {
    title: "Live Channels",
    body: "M3U and XMLTV with a proper programme guide. You supply the playlist; none ships.",
    phase: "Phase 24",
  },
};

/**
 * Honest placeholder (SPEC.md §4: every empty state is designed, never blank).
 * It says which phase makes it real rather than pretending to be finished.
 */
export function Placeholder({ destination }: { destination: Destination }) {
  const copy = COPY[destination];
  return (
    <div className="mx-auto flex h-full max-w-[var(--content-max)] flex-col items-center justify-center gap-4 px-10 text-center">
      <span className="rounded-full border border-line bg-surface px-3 py-1 text-[11px] font-medium uppercase tracking-[0.12em] text-ink-faint">
        {copy.phase}
      </span>
      <h1 className="text-[34px] font-semibold tracking-[-0.02em] text-ink">{copy.title}</h1>
      <p className="max-w-md text-sm leading-relaxed text-ink-muted">{copy.body}</p>
    </div>
  );
}
