//! sin-e-phile — Windows desktop media engine.
//!
//! See `SPEC.md`. This crate is the Rust core; `src/` is the React frontend and
//! the two meet at a **generated** IPC boundary (subtask 1.7).

pub mod commands;
pub mod logging;
pub mod state;
pub mod tiers;

use state::AppState;
use std::sync::OnceLock;
use std::time::Instant;

/// Process start, for an honest cold-start measurement.
///
/// Phase 1's exit criterion is "launches to INTERACTIVE in < 2 s". Timing until
/// the window handle exists would measure window creation, which is a different
/// and flattering number. This is set as early as `run()` begins and read when
/// the frontend reports it has painted.
pub static PROCESS_START: OnceLock<Instant> = OnceLock::new();
use tauri::Manager;
use tauri_specta::{collect_commands, Builder};

/// The IPC surface, in one place.
///
/// SPEC.md Phase 1 requires IPC types to be **generated, not hand-written**, with
/// the exit criterion that "changing a Rust command signature breaks the
/// TypeScript build". That property comes from this list: `tauri-specta` derives
/// the TypeScript from these exact signatures, so a changed argument or return
/// type regenerates `src/lib/ipc.ts`, and any call site that no longer matches
/// fails `tsc`.
///
/// Hand-written bindings would drift silently, and the drift would only show up
/// as a runtime error in front of a user.
fn ipc_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::system::get_hardware_profile,
        commands::system::set_tier_override,
        commands::system::has_capability,
        commands::system::get_data_dir,
        commands::system::debug_trigger_panic,
        commands::system::frontend_ready,
    ])
}

pub fn run() {
    let _ = PROCESS_START.set(Instant::now());

    // Held for the process lifetime: dropping it stops the background log writer
    // and the final lines would be lost.
    let _log_guard = logging::init();

    let builder = ipc_builder();

    // Regenerate the TypeScript bindings on every debug run, so they cannot be
    // stale relative to the Rust. Release builds never write into the source tree.
    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// GENERATED by tauri-specta. Do not edit.\n// Regenerated on every debug run of the Rust backend (see lib.rs).\n"),
            "../src/lib/ipc.ts",
        )
        .expect("failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_window_state::Builder::default().build())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            app.manage(AppState::new());

            // The window stays hidden (tauri.conf.json `visible: false`) until the
            // frontend calls `frontend_ready`, so the user never sees an empty
            // frame during cold start. A watchdog reveals it anyway if the
            // frontend fails, because a permanently invisible window would be a
            // far worse failure than an ugly one.
            let handle = app.handle().clone();
            std::thread::spawn(move || {
                std::thread::sleep(std::time::Duration::from_secs(10));
                if let Some(w) = handle.get_webview_window("main") {
                    if !w.is_visible().unwrap_or(true) {
                        tracing::error!("frontend never reported ready; showing the window anyway");
                        let _ = w.show();
                    }
                }
            });

            tracing::info!(version = env!("CARGO_PKG_VERSION"), "started");
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
